import attributeValidationSchemaCreateAttributeJson from './attributeValidationSchemaCreateAttribute.json';

import attributeValidationSchemaUpdateAttributeJson from './attributeValidationSchemaUpdateAttribute.json';

import attributeValidationSchemaReadAttributeJson from './attributeValidationSchemaReadAttribute.json';

import attributeValidationSchemaDeleteAttributeJson from './attributeValidationSchemaDeleteAttribute.json';

import attributeTypeValidationSchemaCreateAttributeTypeJson from './attributeTypeValidationSchemaCreateAttributeType.json';

import attributeTypeValidationSchemaUpdateAttributeTypeJson from './attributeTypeValidationSchemaUpdateAttributeType.json';

import attributeTypeValidationSchemaReadAttributeTypeJson from './attributeTypeValidationSchemaReadAttributeType.json';

import attributeTypeValidationSchemaDeleteAttributeTypeJson from './attributeTypeValidationSchemaDeleteAttributeType.json';

import resourceAttributeValidationSchemaCreateResourceAttributeJson from './resourceAttributeValidationSchemaCreateResourceAttribute.json';

import resourceAttributeValidationSchemaUpdateResourceAttributeJson from './resourceAttributeValidationSchemaUpdateResourceAttribute.json';

import resourceAttributeValidationSchemaReadResourceAttributeJson from './resourceAttributeValidationSchemaReadResourceAttribute.json';

import resourceAttributeValidationSchemaDeleteResourceAttributeJson from './resourceAttributeValidationSchemaDeleteResourceAttribute.json';

import userAttributeValidationSchemaCreateUserAttributeJson from './userAttributeValidationSchemaCreateUserAttribute.json';

import userAttributeValidationSchemaUpdateUserAttributeJson from './userAttributeValidationSchemaUpdateUserAttribute.json';

import userAttributeValidationSchemaReadUserAttributeJson from './userAttributeValidationSchemaReadUserAttribute.json';

import userAttributeValidationSchemaDeleteUserAttributeJson from './userAttributeValidationSchemaDeleteUserAttribute.json';

export const attributeValidationSchemaCreateAttribute =
  attributeValidationSchemaCreateAttributeJson;

export const attributeValidationSchemaUpdateAttribute =
  attributeValidationSchemaUpdateAttributeJson;

export const attributeValidationSchemaReadAttribute =
  attributeValidationSchemaReadAttributeJson;

export const attributeValidationSchemaDeleteAttribute =
  attributeValidationSchemaDeleteAttributeJson;

export const attributeTypeValidationSchemaCreateAttributeType =
  attributeTypeValidationSchemaCreateAttributeTypeJson;

export const attributeTypeValidationSchemaUpdateAttributeType =
  attributeTypeValidationSchemaUpdateAttributeTypeJson;

export const attributeTypeValidationSchemaReadAttributeType =
  attributeTypeValidationSchemaReadAttributeTypeJson;

export const attributeTypeValidationSchemaDeleteAttributeType =
  attributeTypeValidationSchemaDeleteAttributeTypeJson;

export const resourceAttributeValidationSchemaCreateResourceAttribute =
  resourceAttributeValidationSchemaCreateResourceAttributeJson;

export const resourceAttributeValidationSchemaUpdateResourceAttribute =
  resourceAttributeValidationSchemaUpdateResourceAttributeJson;

export const resourceAttributeValidationSchemaReadResourceAttribute =
  resourceAttributeValidationSchemaReadResourceAttributeJson;

export const resourceAttributeValidationSchemaDeleteResourceAttribute =
  resourceAttributeValidationSchemaDeleteResourceAttributeJson;

export const userAttributeValidationSchemaCreateUserAttribute =
  userAttributeValidationSchemaCreateUserAttributeJson;

export const userAttributeValidationSchemaUpdateUserAttribute =
  userAttributeValidationSchemaUpdateUserAttributeJson;

export const userAttributeValidationSchemaReadUserAttribute =
  userAttributeValidationSchemaReadUserAttributeJson;

export const userAttributeValidationSchemaDeleteUserAttribute =
  userAttributeValidationSchemaDeleteUserAttributeJson;
